// Catálogo real de Alcover Automotores.
// Reconciliado contra la lista de precios interna (fuente de verdad para precio/km/dominio).
// Se dieron de baja los autos del catálogo de WhatsApp que no figuran en la lista de precios
// (Tera High 0km, T-Cross 0km, Virtus 0km, Tracker LT 0km, Taos Confortline 0km, Polo Track 0km 2026):
// eran publicaciones desactualizadas sin respaldo de stock real.
const CATALOGO_ACTUALIZADO = "2026-08-11";

const CATALOGO_ALCOVER = [
  { marca: "Volkswagen", modelo: "Amarok", version: "2.0 180HP 4x2 AT", anio: 2016, km: 158200, esCero: false, dominio: "AA763KF", precio: 27000000, condicion: null, motor: "2.0 (180HP)", caja: "Automática", specs: ["Único dueño"] },
  { marca: "Volkswagen", modelo: "T-Cross", version: "Trendline 1.6 Blanca", anio: 2022, km: 66000, esCero: false, dominio: "AF257KT", precio: 26700000, condicion: "Consignación", motor: "1.6", caja: null, specs: ["Aire y dirección", "Cierre centralizado y alarma", "Pantalla táctil", "Sensores de estacionamiento"] },
  { marca: "Renault", modelo: "Duster Oroch", version: "Outsider 1.6 GNC", anio: 2019, km: 128000, esCero: false, dominio: "AD880HR", precio: 21500000, condicion: "Consignación", motor: "1.6", caja: null, specs: ["Equipo de GNC"] },
  { marca: "Fiat", modelo: "Palio", version: "Atractive 1.4", anio: 2017, km: 59000, esCero: false, dominio: "AB842UQ", precio: 15500000, condicion: "Consignación", motor: "1.4", caja: null, specs: ["Aire y dirección", "Cierre centralizado y alarma", "Levanta vidrios electrónicos", "Llantas de aleación"] },
  { marca: "Volkswagen", modelo: "Suran", version: "Trendline 1.6", anio: 2017, km: 174000, esCero: false, dominio: "AC731GM", precio: 17500000, condicion: null, motor: "1.6", caja: null, specs: ["Aire y dirección", "Cierre centralizado y alarma", "Levanta vidrios eléctricos"] },
  { marca: "Volkswagen", modelo: "Virtus", version: "GTS 1.4 Turbo AT", anio: 2022, km: 126000, esCero: false, dominio: "AF223GF", precio: 31000000, condicion: null, motor: "1.4 turbo", caja: "Automática", specs: ["Cubiertas nuevas"] },
  { marca: "Volkswagen", modelo: "Fox", version: "Connect 1.6", anio: 2018, km: 86000, esCero: false, dominio: "AC739GE", precio: 19600000, condicion: null, motor: "1.6", caja: null, specs: ["Pantalla táctil", "Aire y dirección", "Cierre centralizado y alarma", "Levanta vidrios eléctricos"] },
  { marca: "Peugeot", modelo: "408", version: "Allure Plus 1.6 Turbo", anio: 2019, km: 58500, esCero: false, dominio: "AD853QE", precio: 16900000, condicion: "Consignación", motor: "1.6 turbo", caja: null, specs: ["Tapizado de cuero", "Techo corredizo", "Climatizador Bizona", "Único dueño"] },
  { marca: "Ford", modelo: "Fiesta", version: "SE 1.6", anio: 2019, km: 76000, esCero: false, dominio: "AD384BI", precio: 20300000, condicion: "Consignación", motor: "1.6", caja: null, specs: ["Aire y dirección", "Cierre centralizado y alarma"] },
  { marca: "Peugeot", modelo: "208", version: "Feline", anio: 2020, km: 54000, esCero: false, dominio: "AE057DK", precio: 20600000, condicion: null, motor: "1.6", caja: null, specs: ["Pantalla táctil", "Sensores y cámara de estacionamiento", "Techo panorámico corredizo"] },
  { marca: "Chevrolet", modelo: "S10", version: "High Country 4x2 Manual", anio: 2017, km: 151000, esCero: false, dominio: "AB366SS", precio: 29500000, condicion: "Agencia", motor: "2.8", caja: "Manual", traccion: "4x2", specs: ["Tapizado de cuero", "Pantalla con sensores y cámara"] },
  { marca: "Volkswagen", modelo: "Amarok", version: "Trendline 4x2 2.0", anio: 2024, km: 28000, esCero: false, dominio: "AG818BK", precio: 36600000, condicion: null, motor: "2.0 (140HP)", caja: null, traccion: "4x2", specs: ["Pantalla táctil", "Tapizado simil cuero", "Aire y dirección", "Levanta vidrios eléctricos"], destacado: true },
  { marca: "Chevrolet", modelo: "Cruze", version: "1.4 Turbo LT MT", anio: 2017, km: 71822, esCero: false, dominio: "AB668OG", precio: 21200000, condicion: "Consignación", motor: "1.4 Turbo", caja: "Manual", specs: ["Tapizado de cuero", "Pantalla, cámara y sensores de estacionamiento"] },
  { marca: "Volkswagen", modelo: "Polo Track", version: null, anio: 2024, km: 62200, esCero: false, dominio: "AG953CO", precio: 23500000, condicion: null, motor: "1.6", caja: null, specs: ["Pantalla táctil con CarPlay", "Aire y dirección", "Cierre centralizado y alarma", "Levanta vidrios en puertas delanteras"] },
  { marca: "Volkswagen", modelo: "Golf", version: "Bluemotion Tecno DSG 1.4 TSI", anio: 2015, km: null, esCero: false, dominio: "PLU532", precio: 22000000, condicion: null, motor: "1.4 TSI", caja: "DSG Automática", specs: ["Stage 1 - Escape Silen", "Sensores de estacionamiento traseros y delanteros"] },
  { marca: "Toyota", modelo: "Yaris", version: "XS AT", anio: 2025, km: 0, esCero: true, dominio: "AH962IG", precio: 36900000, condicion: null, motor: "1.5 cadenero", caja: "Automática", specs: ["0km patentado", "Pantalla táctil"] },
  { marca: "Fiat", modelo: "Argo", version: "Drive 1.3", anio: 2018, km: 100000, esCero: false, dominio: "AC977HC", precio: 18500000, condicion: null, motor: "1.3 cadenero", caja: null, specs: ["Aire y dirección electrónica", "Pantalla táctil", "Sensores de estacionamiento"] },
  { marca: "Toyota", modelo: "Hilux", version: "DX 2.4 4x4", anio: 2025, km: 0, esCero: true, dominio: "AH962GH", precio: 56900000, condicion: null, motor: "2.4", caja: "Manual 6ta", traccion: "4x4", specs: ["Patentada", "Pantalla táctil con CarPlay"], destacado: true },
  { marca: "Toyota", modelo: "Hilux", version: "SR 2.4 4x2", anio: 2025, km: 0, esCero: true, dominio: "AH343NU", precio: 56900000, condicion: null, motor: "2.4", caja: "Manual 6ta", traccion: "4x2", specs: ["Patentada", "Pantalla táctil con CarPlay", "Cámara de estacionamiento"], destacado: true },
  { marca: "Fiat", modelo: "Uno", version: "Fire 1.3 Base", anio: 2013, km: 129000, esCero: false, dominio: "MPO698", precio: 8500000, condicion: "Consignación", motor: "1.3 Fire", caja: null, specs: ["Único dueño"] },
  { marca: "Fiat", modelo: "Cronos", version: "Precision 1.8", anio: 2022, km: 54000, esCero: false, dominio: "AF426TR", precio: 21600000, condicion: "Agencia", motor: "1.8 cadenero", caja: null, specs: ["Tapizado de cuero", "Climatizador", "Pantalla táctil", "Cámara y sensores de estacionamiento", "Llantas de aleación", "4 cubiertas nuevas"] },
  { marca: "Fiat", modelo: "Toro", version: "Freedom 1.8 AT", anio: 2023, km: 75600, esCero: false, dominio: "AF789RZ", precio: 30600000, condicion: null, motor: "1.8", caja: "Automática", specs: ["Tapizado de cuero", "Pantalla con cámara y sensores"] },
  { marca: "Volkswagen", modelo: "Gol", version: "Trend Trendline Rojo", anio: 2019, km: 100000, esCero: false, dominio: "AD701CW", precio: 18200000, condicion: null, motor: "1.6", caja: null, specs: ["Aire y dirección", "Levanta vidrios eléctricos delanteros", "Cierre centralizado y alarma", "Dos cubiertas nuevas"] },
  { marca: "Renault", modelo: "Sandero", version: "Stepway Privilege 1.6", anio: 2017, km: 129000, esCero: false, dominio: "AB188KV", precio: 17200000, condicion: null, motor: "1.6", caja: null, specs: ["Pantalla táctil", "Cubiertas nuevas"] },
  { marca: "Fiat", modelo: "Mobi", version: "Way 1.0", anio: 2018, km: 128000, esCero: false, dominio: "AC331ND", precio: 14200000, condicion: null, motor: "1.0", caja: null, specs: ["Aire y dirección", "Cierre centralizado y alarma", "Levanta vidrios eléctricos"] },
  { marca: "Ford", modelo: "Ka", version: "Freestyle SEL 1.5", anio: 2020, km: 100000, esCero: false, dominio: "AE292BV", precio: 20600000, condicion: null, motor: "1.5", caja: null, specs: ["Tapizado de cuero", "Pantalla táctil", "Cámara y sensores", "Cubiertas y correa nueva"] },
  { marca: "Volkswagen", modelo: "Taos", version: "Highline Hero 250 TSI AT", anio: 2022, km: 116000, esCero: false, dominio: "AF716BM", precio: 43000000, condicion: null, motor: "1.4 turbo", caja: "Automática", specs: ["Techo panorámico corredizo", "Tapizados de cuero", "Sensores y cámara de estacionamiento"], destacado: true },
  { marca: "Renault", modelo: "Sandero", version: "RS 2.0", anio: 2018, km: 84200, esCero: false, dominio: "AC558GE", precio: 19600000, condicion: "Agencia", motor: "2.0", caja: "6ta", specs: ["Pantalla táctil", "Sensores de estacionamiento"] },
  { marca: "Fiat", modelo: "Cronos", version: "Drive Pack GSE BZ", anio: 2026, km: 2000, esCero: true, dominio: "AI049OG", precio: 32600000, condicion: null, motor: null, caja: null, specs: ["Patentado"] },
  { marca: "Ford", modelo: "Ecosport", version: "SE 1.6", anio: 2016, km: 127000, esCero: false, dominio: "AA435BQ", precio: 17600000, condicion: null, motor: "1.6", caja: null, specs: ["Aire y dirección", "Cierre centralizado y alarma", "Levanta vidrios eléctricos", "Faros auxiliares antiniebla"] },
  { marca: "Chevrolet", modelo: "Tracker", version: "LTZ 1.8 4x4", anio: 2017, km: 134000, esCero: false, dominio: "AA872RK", precio: 18900000, condicion: "Consignación", motor: "1.8", caja: null, specs: ["Tapizado de cuero", "Techo corredizo", "Sensores y cámara de estacionamiento"] },
  { marca: "Volkswagen", modelo: "Amarok", version: "Extreme V6 258HP", anio: 2020, km: 98000, esCero: false, dominio: "AE434WK", precio: 50000000, condicion: null, motor: "3.0 (258HP)", caja: "Automática", specs: ["Tapizado de cuero", "Butacas calefaccionadas", "Cámara y sensores de estacionamiento"], destacado: true },
];

if (typeof window !== "undefined") {
  window.CATALOGO_ALCOVER = CATALOGO_ALCOVER;
  window.CATALOGO_ACTUALIZADO = CATALOGO_ACTUALIZADO;
}
